// <auto-generated />
using System;
using DunesOfArabia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DunesOfArabia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524210911_AddComplaintCategoryAndDescription")]
    partial class AddComplaintCategoryAndDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DunesOfArabia.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationPolicy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationId1")
                        .HasColumnType("int");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DurationHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncludedServices")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatorEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatorPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceSAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("DestinationId1");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CancellationPolicy = "",
                            Category = "Adventure",
                            Description = "Experience the best of AlUla with a combination of archaeological tours, desert adventures, and cultural immersion.",
                            DestinationId = 3,
                            DifficultyLevel = "",
                            DurationHours = 8m,
                            ImageUrl = "https://images.unsplash.com/photo-1616236197457-53e96373d0b0?w=900",
                            IncludedServices = "",
                            MaxParticipants = 20,
                            MinAge = 0,
                            Name = "AlUla Heritage & Adventure Combo",
                            OperatorEmail = "",
                            OperatorName = "",
                            OperatorPhone = "",
                            PriceSAR = 350m,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 2,
                            CancellationPolicy = "",
                            Category = "Adventure",
                            Description = "Thrilling off-road desert adventure through vast golden dunes with expert guides and traditional refreshments.",
                            DestinationId = 7,
                            DifficultyLevel = "",
                            DurationHours = 5m,
                            ImageUrl = "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=700",
                            IncludedServices = "",
                            MaxParticipants = 20,
                            MinAge = 0,
                            Name = "Desert Safari",
                            OperatorEmail = "",
                            OperatorName = "",
                            OperatorPhone = "",
                            PriceSAR = 150m,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 3,
                            CancellationPolicy = "",
                            Category = "Adventure",
                            Description = "Scale spectacular sandstone formations and canyon walls with certified climbing instructors.",
                            DestinationId = 8,
                            DifficultyLevel = "",
                            DurationHours = 3m,
                            ImageUrl = "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=700",
                            IncludedServices = "",
                            MaxParticipants = 20,
                            MinAge = 0,
                            Name = "Rock Climbing",
                            OperatorEmail = "",
                            OperatorName = "",
                            OperatorPhone = "",
                            PriceSAR = 120m,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 4,
                            CancellationPolicy = "",
                            Category = "Adventure",
                            Description = "Heart-pumping 4x4 ride across towering dunes in the vast Empty Quarter desert.",
                            DestinationId = 7,
                            DifficultyLevel = "",
                            DurationHours = 2m,
                            ImageUrl = "https://images.unsplash.com/photo-1542401886-65d6c61db217?w=700",
                            IncludedServices = "",
                            MaxParticipants = 20,
                            MinAge = 0,
                            Name = "Dune Bashing",
                            OperatorEmail = "",
                            OperatorName = "",
                            OperatorPhone = "",
                            PriceSAR = 100m,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 5,
                            CancellationPolicy = "",
                            Category = "Cultural",
                            Description = "Guided walk through Diriyah's ancient mud-brick At-Turaif district with a local historian.",
                            DestinationId = 4,
                            DifficultyLevel = "",
                            DurationHours = 3m,
                            ImageUrl = "https://images.unsplash.com/photo-1539667284076-a4d98d9ac42b?w=700",
                            IncludedServices = "",
                            MaxParticipants = 20,
                            MinAge = 0,
                            Name = "Heritage Walking Tour",
                            OperatorEmail = "",
                            OperatorName = "",
                            OperatorPhone = "",
                            PriceSAR = 90m,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 6,
                            CancellationPolicy = "",
                            Category = "Cultural",
                            Description = "Explore labyrinthine souqs, taste local spices, and shop handcrafted Saudi treasures.",
                            DestinationId = 2,
                            DifficultyLevel = "",
                            DurationHours = 2m,
                            ImageUrl = "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=700",
                            IncludedServices = "",
                            MaxParticipants = 20,
                            MinAge = 0,
                            Name = "Traditional Souq Experience",
                            OperatorEmail = "",
                            OperatorName = "",
                            OperatorPhone = "",
                            PriceSAR = 70m,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 7,
                            CancellationPolicy = "",
                            Category = "Cultural",
                            Description = "Walk among Nabataean tombs and ancient inscriptions at AlUla's UNESCO World Heritage sites.",
                            DestinationId = 3,
                            DifficultyLevel = "",
                            DurationHours = 4m,
                            ImageUrl = "https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=700",
                            IncludedServices = "",
                            MaxParticipants = 20,
                            MinAge = 0,
                            Name = "Archaeological Site Visit",
                            OperatorEmail = "",
                            OperatorName = "",
                            OperatorPhone = "",
                            PriceSAR = 110m,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 8,
                            CancellationPolicy = "",
                            Category = "Water",
                            Description = "Dive into pristine Red Sea coral reefs teeming with vibrant marine life and stunning underwater formations.",
                            DestinationId = 12,
                            DifficultyLevel = "",
                            DurationHours = 3m,
                            ImageUrl = "https://images.unsplash.com/photo-1564769611905-cd27ee64e59b?w=700",
                            IncludedServices = "",
                            MaxParticipants = 20,
                            MinAge = 0,
                            Name = "Scuba Diving",
                            OperatorEmail = "",
                            OperatorName = "",
                            OperatorPhone = "",
                            PriceSAR = 200m,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 9,
                            CancellationPolicy = "",
                            Category = "Water",
                            Description = "Snorkel through crystal-clear waters above spectacular coral gardens and tropical fish.",
                            DestinationId = 12,
                            DifficultyLevel = "",
                            DurationHours = 3m,
                            ImageUrl = "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=700",
                            IncludedServices = "",
                            MaxParticipants = 20,
                            MinAge = 0,
                            Name = "Snorkeling Adventure",
                            OperatorEmail = "",
                            OperatorName = "",
                            OperatorPhone = "",
                            PriceSAR = 90m,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 10,
                            CancellationPolicy = "",
                            Category = "Desert",
                            Description = "Ride through golden sands atop a camel as the desert sun paints the dunes a brilliant crimson.",
                            DestinationId = 7,
                            DifficultyLevel = "",
                            DurationHours = 2m,
                            ImageUrl = "https://images.unsplash.com/photo-1549880338-65ddcdfd017b?w=700",
                            IncludedServices = "",
                            MaxParticipants = 20,
                            MinAge = 0,
                            Name = "Camel Trekking",
                            OperatorEmail = "",
                            OperatorName = "",
                            OperatorPhone = "",
                            PriceSAR = 100m,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 11,
                            CancellationPolicy = "",
                            Category = "Desert",
                            Description = "Witness a breathtaking canopy of stars far from city lights, deep in the Arabian desert.",
                            DestinationId = 9,
                            DifficultyLevel = "",
                            DurationHours = 2m,
                            ImageUrl = "https://images.unsplash.com/photo-1446941303997-2843d7b4d20f?w=700",
                            IncludedServices = "",
                            MaxParticipants = 20,
                            MinAge = 0,
                            Name = "Stargazing Experience",
                            OperatorEmail = "",
                            OperatorName = "",
                            OperatorPhone = "",
                            PriceSAR = 80m,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 12,
                            CancellationPolicy = "",
                            Category = "Desert",
                            Description = "Spend an evening in a traditional Bedouin camp with dinner, cultural music, and desert tales.",
                            DestinationId = 9,
                            DifficultyLevel = "",
                            DurationHours = 8m,
                            ImageUrl = "https://images.unsplash.com/photo-1519671282429-b44b0de7773e?w=700",
                            IncludedServices = "",
                            MaxParticipants = 20,
                            MinAge = 0,
                            Name = "Bedouin Camp Experience",
                            OperatorEmail = "",
                            OperatorName = "",
                            OperatorPhone = "",
                            PriceSAR = 180m,
                            Rating = 0.0
                        });
                });

            modelBuilder.Entity("DunesOfArabia.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DunesOfArabia.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfTravelers")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePaymentIntentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("DestinationId1");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DunesOfArabia.Models.BookingDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingDocuments");
                });

            modelBuilder.Entity("DunesOfArabia.Models.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("DunesOfArabia.Models.DailyActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryId");

                    b.ToTable("DailyActivities");
                });

            modelBuilder.Entity("DunesOfArabia.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BestSeason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Climate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighlightsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageGallery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageGalleryJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisaInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BestSeason = "November to February",
                            Category = "Urban",
                            Climate = "Hot, Arid",
                            Cost = 800m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The modern capital blending innovation with rich cultural heritage and historic landmarks.",
                            HighlightsJson = "[]",
                            ImageGallery = "[]",
                            ImageGalleryJson = "",
                            ImageUrl = "https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?w=800",
                            Latitude = 24.6877,
                            Longitude = 46.721899999999998,
                            Name = "Riyadh",
                            Province = "Central Region",
                            Rating = 4.7999999999999998,
                            Temperature = "20°C – 45°C",
                            VisaInfo = "Tourist Visa Available"
                        },
                        new
                        {
                            Id = 2,
                            BestSeason = "October to April",
                            Category = "Coastal",
                            Climate = "Hot, Humid",
                            Cost = 700m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Historic port city with beautiful coastline, vibrant culture, and world-class diving.",
                            HighlightsJson = "[]",
                            ImageGallery = "[]",
                            ImageGalleryJson = "",
                            ImageUrl = "https://images.unsplash.com/photo-1539667284076-a4d98d9ac42b?w=800",
                            Latitude = 21.485800000000001,
                            Longitude = 39.192500000000003,
                            Name = "Jeddah",
                            Province = "Red Sea Coast",
                            Rating = 4.7000000000000002,
                            Temperature = "22°C – 40°C",
                            VisaInfo = "Tourist Visa Available"
                        },
                        new
                        {
                            Id = 3,
                            BestSeason = "October to March",
                            Category = "Historical",
                            Climate = "Hot, Dry",
                            Cost = 1200m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ancient rock formations and UNESCO World Heritage sites in a stunning desert landscape.",
                            HighlightsJson = "[]",
                            ImageGallery = "[]",
                            ImageGalleryJson = "",
                            ImageUrl = "https://images.unsplash.com/photo-1616236197457-53e96373d0b0?w=800",
                            Latitude = 26.609999999999999,
                            Longitude = 37.920000000000002,
                            Name = "AlUla",
                            Province = "Al Madinah Region",
                            Rating = 4.9000000000000004,
                            Temperature = "10°C – 38°C",
                            VisaInfo = "Tourist Visa Available"
                        },
                        new
                        {
                            Id = 4,
                            BestSeason = "November to February",
                            Category = "Historical",
                            Climate = "Hot, Arid",
                            Cost = 500m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The birthplace of the Kingdom with beautifully preserved mud-brick architecture.",
                            HighlightsJson = "[]",
                            ImageGallery = "[]",
                            ImageGalleryJson = "",
                            ImageUrl = "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800",
                            Latitude = 24.734400000000001,
                            Longitude = 46.575400000000002,
                            Name = "Diriyah",
                            Province = "Riyadh Province",
                            Rating = 4.5999999999999996,
                            Temperature = "18°C – 44°C",
                            VisaInfo = "Tourist Visa Available"
                        },
                        new
                        {
                            Id = 5,
                            BestSeason = "October to March",
                            Category = "Historical",
                            Climate = "Hot, Dry",
                            Cost = 950m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Saudi Arabia's first UNESCO World Heritage Site with breathtaking Nabataean tombs carved into sandstone.",
                            HighlightsJson = "[]",
                            ImageGallery = "[]",
                            ImageGalleryJson = "",
                            ImageUrl = "https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=800",
                            Latitude = 26.791399999999999,
                            Longitude = 37.9529,
                            Name = "Hegra (Mada'in Saleh)",
                            Province = "Al Madinah Region",
                            Rating = 4.7999999999999998,
                            Temperature = "10°C – 38°C",
                            VisaInfo = "Tourist Visa Available"
                        },
                        new
                        {
                            Id = 6,
                            BestSeason = "October to March",
                            Category = "Historical",
                            Climate = "Hot, Dry",
                            Cost = 600m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A labyrinth of mud-brick houses dating back 2,000 years, abandoned and eerily preserved in the desert.",
                            HighlightsJson = "[]",
                            ImageGallery = "[]",
                            ImageGalleryJson = "",
                            ImageUrl = "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800",
                            Latitude = 26.587,
                            Longitude = 37.916800000000002,
                            Name = "Al Ula Old Town",
                            Province = "Al Madinah Region",
                            Rating = 4.5,
                            Temperature = "10°C – 38°C",
                            VisaInfo = "Tourist Visa Available"
                        },
                        new
                        {
                            Id = 7,
                            BestSeason = "November to February",
                            Category = "Desert",
                            Climate = "Extremely Hot, Arid",
                            Cost = 1100m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The world's largest continuous sand desert offering unparalleled adventure experiences.",
                            HighlightsJson = "[]",
                            ImageGallery = "[]",
                            ImageGalleryJson = "",
                            ImageUrl = "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800",
                            Latitude = 20.0,
                            Longitude = 50.0,
                            Name = "Empty Quarter",
                            Province = "Southern Saudi Arabia",
                            Rating = 4.5,
                            Temperature = "15°C – 50°C",
                            VisaInfo = "Tourist Visa Available"
                        },
                        new
                        {
                            Id = 8,
                            BestSeason = "October to April",
                            Category = "Desert",
                            Climate = "Hot, Dry",
                            Cost = 900m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dramatic red-sand valleys and towering sandstone pillars stretching to the horizon.",
                            HighlightsJson = "[]",
                            ImageGallery = "[]",
                            ImageGalleryJson = "",
                            ImageUrl = "https://images.unsplash.com/photo-1519671282429-b44b0de7773e?w=800",
                            Latitude = 29.575500000000002,
                            Longitude = 35.423699999999997,
                            Name = "Wadi Rum",
                            Province = "Tabuk Region",
                            Rating = 4.7000000000000002,
                            Temperature = "10°C – 38°C",
                            VisaInfo = "Tourist Visa Available"
                        },
                        new
                        {
                            Id = 9,
                            BestSeason = "November to March",
                            Category = "Desert",
                            Climate = "Hot, Arid",
                            Cost = 750m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vast crescent-shaped dunes with striking reddish-orange sands unique to northern Arabia.",
                            HighlightsJson = "[]",
                            ImageGallery = "[]",
                            ImageGalleryJson = "",
                            ImageUrl = "https://images.unsplash.com/photo-1542401886-65d6c61db217?w=800",
                            Latitude = 28.0,
                            Longitude = 41.0,
                            Name = "Al Nafud Desert",
                            Province = "Northern Region",
                            Rating = 4.2999999999999998,
                            Temperature = "8°C – 42°C",
                            VisaInfo = "Tourist Visa Available"
                        },
                        new
                        {
                            Id = 10,
                            BestSeason = "April to October",
                            Category = "Mountain",
                            Climate = "Mild, Temperate",
                            Cost = 650m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lush green mountains with a cooler climate, terraced farms, and breathtaking natural landscapes.",
                            HighlightsJson = "[]",
                            ImageGallery = "[]",
                            ImageGalleryJson = "",
                            ImageUrl = "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
                            Latitude = 18.2164,
                            Longitude = 42.505299999999998,
                            Name = "Asir Mountains",
                            Province = "Southwestern Saudi Arabia",
                            Rating = 4.7000000000000002,
                            Temperature = "12°C – 30°C",
                            VisaInfo = "Tourist Visa Available"
                        },
                        new
                        {
                            Id = 11,
                            BestSeason = "March to October",
                            Category = "Mountain",
                            Climate = "Mild",
                            Cost = 400m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mountain resort city famous for its rose gardens, cool summer retreats, and pleasant weather year-round.",
                            HighlightsJson = "[]",
                            ImageGallery = "[]",
                            ImageGalleryJson = "",
                            ImageUrl = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
                            Latitude = 21.270299999999999,
                            Longitude = 40.415799999999997,
                            Name = "Taif",
                            Province = "Makkah Province",
                            Rating = 4.4000000000000004,
                            Temperature = "15°C – 35°C",
                            VisaInfo = "Tourist Visa Available"
                        },
                        new
                        {
                            Id = 12,
                            BestSeason = "October to April",
                            Category = "Nature",
                            Climate = "Hot, Humid",
                            Cost = 850m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pristine coral reefs, crystal-clear waters, and rare wildlife in a protected Red Sea marine reserve.",
                            HighlightsJson = "[]",
                            ImageGallery = "[]",
                            ImageGalleryJson = "",
                            ImageUrl = "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800",
                            Latitude = 16.699999999999999,
                            Longitude = 41.966700000000003,
                            Name = "Farasan Islands",
                            Province = "Jizan Region",
                            Rating = 4.5999999999999996,
                            Temperature = "24°C – 38°C",
                            VisaInfo = "Tourist Visa Available"
                        },
                        new
                        {
                            Id = 13,
                            BestSeason = "November to February",
                            Category = "Nature",
                            Climate = "Hot, Arid",
                            Cost = 350m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The world's largest oasis with sprawling date palm gardens and natural artesian springs.",
                            HighlightsJson = "[]",
                            ImageGallery = "[]",
                            ImageGalleryJson = "",
                            ImageUrl = "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800",
                            Latitude = 25.381399999999999,
                            Longitude = 49.586399999999998,
                            Name = "Al-Ahsa Oasis",
                            Province = "Eastern Province",
                            Rating = 4.2999999999999998,
                            Temperature = "12°C – 45°C",
                            VisaInfo = "Tourist Visa Available"
                        },
                        new
                        {
                            Id = 14,
                            BestSeason = "October to April",
                            Category = "Coastal",
                            Climate = "Hot, Humid",
                            Cost = 2200m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pristine islands and turquoise waters home to a new world-class luxury eco-tourism destination.",
                            HighlightsJson = "[]",
                            ImageGallery = "[]",
                            ImageGalleryJson = "",
                            ImageUrl = "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800",
                            Latitude = 28.0,
                            Longitude = 35.149999999999999,
                            Name = "Red Sea Project",
                            Province = "Western Coast",
                            Rating = 4.7999999999999998,
                            Temperature = "22°C – 38°C",
                            VisaInfo = "Tourist Visa Available"
                        },
                        new
                        {
                            Id = 15,
                            BestSeason = "October to April",
                            Category = "Coastal",
                            Climate = "Hot, Humid",
                            Cost = 500m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A laid-back Red Sea city with beautiful coral reefs, clear waters, and a charming historic old town.",
                            HighlightsJson = "[]",
                            ImageGallery = "[]",
                            ImageGalleryJson = "",
                            ImageUrl = "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
                            Latitude = 24.089300000000001,
                            Longitude = 38.061799999999998,
                            Name = "Yanbu",
                            Province = "Al Madinah Region",
                            Rating = 4.2000000000000002,
                            Temperature = "20°C – 40°C",
                            VisaInfo = "Tourist Visa Available"
                        },
                        new
                        {
                            Id = 16,
                            BestSeason = "November to March",
                            Category = "Coastal",
                            Climate = "Hot, Humid",
                            Cost = 300m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vibrant waterfront promenade with fresh seafood, mangrove walks, and island day trips.",
                            HighlightsJson = "[]",
                            ImageGallery = "[]",
                            ImageGalleryJson = "",
                            ImageUrl = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
                            Latitude = 16.889199999999999,
                            Longitude = 42.551099999999998,
                            Name = "Jizan Corniche",
                            Province = "Jizan Region",
                            Rating = 4.0999999999999996,
                            Temperature = "22°C – 38°C",
                            VisaInfo = "Tourist Visa Available"
                        },
                        new
                        {
                            Id = 17,
                            BestSeason = "November to March",
                            Category = "Urban",
                            Climate = "Hot, Humid",
                            Cost = 550m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A modern city on the Arabian Gulf known for its waterfront promenade and cosmopolitan dining.",
                            HighlightsJson = "[]",
                            ImageGallery = "[]",
                            ImageGalleryJson = "",
                            ImageUrl = "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800",
                            Latitude = 26.217199999999998,
                            Longitude = 50.197099999999999,
                            Name = "Al Khobar",
                            Province = "Eastern Province",
                            Rating = 4.2000000000000002,
                            Temperature = "18°C – 42°C",
                            VisaInfo = "Tourist Visa Available"
                        },
                        new
                        {
                            Id = 18,
                            BestSeason = "October to April",
                            Category = "Urban",
                            Climate = "Hot, Arid",
                            Cost = 1800m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The future city of Saudi Arabia — a futuristic mega-project amidst dramatic desert and coastal scenery.",
                            HighlightsJson = "[]",
                            ImageGallery = "[]",
                            ImageGalleryJson = "",
                            ImageUrl = "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800",
                            Latitude = 28.033899999999999,
                            Longitude = 35.513599999999997,
                            Name = "NEOM & Tabuk Region",
                            Province = "Tabuk Region",
                            Rating = 4.5999999999999996,
                            Temperature = "15°C – 40°C",
                            VisaInfo = "Tourist Visa Available"
                        });
                });

            modelBuilder.Entity("DunesOfArabia.Models.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Travelers")
                        .HasColumnType("int");

                    b.Property<string>("TripType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Itineraries");
                });

            modelBuilder.Entity("DunesOfArabia.Models.PackingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPacked")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryId");

                    b.ToTable("PackingItems");
                });

            modelBuilder.Entity("DunesOfArabia.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationId1")
                        .HasColumnType("int");

                    b.Property<int>("StarRating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("DestinationId1");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("DunesOfArabia.Models.UserFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationId1")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("DestinationId1");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DunesOfArabia.Models.Activity", b =>
                {
                    b.HasOne("DunesOfArabia.Models.Destination", null)
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DunesOfArabia.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId1");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("DunesOfArabia.Models.Booking", b =>
                {
                    b.HasOne("DunesOfArabia.Models.Destination", null)
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DunesOfArabia.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId1");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("DunesOfArabia.Models.BookingDocument", b =>
                {
                    b.HasOne("DunesOfArabia.Models.Booking", "Booking")
                        .WithMany("Documents")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("DunesOfArabia.Models.DailyActivity", b =>
                {
                    b.HasOne("DunesOfArabia.Models.Itinerary", "Itinerary")
                        .WithMany("Activities")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("DunesOfArabia.Models.Itinerary", b =>
                {
                    b.HasOne("DunesOfArabia.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("DunesOfArabia.Models.PackingItem", b =>
                {
                    b.HasOne("DunesOfArabia.Models.Itinerary", "Itinerary")
                        .WithMany("PackingItems")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("DunesOfArabia.Models.Review", b =>
                {
                    b.HasOne("DunesOfArabia.Models.Destination", null)
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DunesOfArabia.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId1");

                    b.HasOne("DunesOfArabia.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DunesOfArabia.Models.UserFavorite", b =>
                {
                    b.HasOne("DunesOfArabia.Models.Destination", null)
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DunesOfArabia.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId1");

                    b.HasOne("DunesOfArabia.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DunesOfArabia.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DunesOfArabia.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DunesOfArabia.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DunesOfArabia.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DunesOfArabia.Models.Booking", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("DunesOfArabia.Models.Itinerary", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("PackingItems");
                });
#pragma warning restore 612, 618
        }
    }
}
